---
- name: Setup SNOW Custom Credential Type
  awx.awx.tower_credential_type:
    name: ServiceNow
    description: Credentials type for ServiceNow
    kind: cloud
    inputs: "{{ lookup('file', 'files/inputs_snow.yml') | from_yaml }}"
    injectors: "{{ lookup('file', 'files/injectors_snow.yml') | from_yaml }}"
    state: present
    validate_certs: true
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"

- name: Add SNOW custom credential
  awx.awx.tower_credential:
    name: SNOW 
    credential_type: ServiceNow 
    organization: Default 
    inputs:
      username: "{{ snow_username }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true