---
- name: Setup ServiceNow demo 
  hosts: localhost
  connection: local 
  vars:
    snow_instance: "{{ survey_snow_instance }}"
    snow_username: "{{ survey_snow_username }}"
    snow_password: "{{ survey_snow_password }}"
    
  tasks:
    - name: Setup ServiceNow custom credential 
      include_role:
        name: snow-credential 

    - name: Setup ServiceNow compliance closed loop demo
      include_role:
        name: snow-compliance
