---
- name: Setup SNOW Custom Credential 
  awx.awx.tower_credential_type:
    name: ServiceNow
    description: Credentials type for ServiceNow
    kind: cloud
    inputs: 
      fields:
      - type: string
        id: username
        label: SN_USERNAME
      - secret: true
        type: string
        id: password
        label: SN_PASSWORD
      - type: string
        id: instance
        label: SN_INSTANCE
    injectors: 
      env:
        SN_INSTANCE: '{{ instance }}'
        SN_PASSWORD: '{{ password }}'
        SN_USERNAME: '{{ username }}'
      extra_vars:
        SN_INSTANCE: '{{ instance }}'
        SN_PASSWORD: '{{ password }}'
        SN_USERNAME: '{{ username }}'
    state: present
    validate_certs: false
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: Add custom credential
  awx.awx.tower_credential:
    name: SNOW Credential 
    credential_type: SNOW_CL Credential 
    organization: Default 
    inputs:
      username: "{{ username }}"
      password: "{{ password }}"
      instance: "{{ instance }}"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true