---
- name: Setup SNOW Custom Credential 
  awx.awx.tower_credential_type:
    name: ServiceNow
    description: Credentials type for ServiceNow
    kind: cloud
    inputs: "{{ lookup('file', 'inputs_snow.yml') }}"
    injectors: "{{ lookup('file', 'injectors_snow.yml') }}"
    state: present
    validate_certs: false
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true

- name: Add custom credential
  awx.awx.tower_credential:
    name: SNOW Credential 
    credential_type: SNOW_CL Credential 
    organization: Default 
    inputs:
      username: "{{ username }}"
      password: "{{ password }}"
      instance: "{{ instance }}"
    tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
    tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
    tower_host: "{{ lookup('env', 'TOWER_HOST') }}"
    tower_verify_ssl: true